tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "bitwarden-cli"
brew "dockutil"
brew "gitversion"
brew "gnupg"
brew "mas"
cask "adobe-acrobat-pro"
cask "aws-vpn-client"
cask "azure-data-studio"
cask "brave-browser"
cask "discord"
cask "docker"
cask "firefox"
cask "gitkraken"
cask "google-chrome"
cask "iterm2"
cask "krisp"
cask "microsoft-teams"
cask "powershell"
cask "powershell-preview"
cask "slack"
cask "surfshark"
cask "tailscale"
cask "telegram"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "Bitwarden", id: 1352778147
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
