tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "bitwarden-cli"
brew "dockutil"
brew "gitversion"
brew "gnupg"
brew "mas"
cask "adobe-acrobat-pro"
cask "aws-vpn-client"
cask "azure-data-studio"
cask "brave-browser"
cask "camtasia"
cask "daisydisk"
cask "discord"
cask "docker"
cask "elgato-stream-deck"
cask "firefox"
cask "gitkraken"
cask "google-chrome"
cask "intune-company-portal"
cask "iterm2"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "microsoft-edge"
cask "microsoft-office"
cask "parallels"
cask "powershell"
cask "powershell-preview"
cask "slack"
cask "surfshark"
cask "tailscale"
cask "telegram"
cask "transmit"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "Apple Configurator", id: 1037126344
mas "Bitwarden", id: 1352778147
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft To Do", id: 1274495053
mas "Xcode", id: 497799835
